# --- !Ups

create table "widgets" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "price" int not null
);

insert into "widgets" values (default, 'Saratoga Pale Ale', '12');
insert into "widgets" values (default, 'San Jose IPA', '11');
insert into "widgets" values (default, 'Santa Clara Lager', '9');

# --- !Downs

drop table "widgets" if exists;