# --- !Ups

create table "widget" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "price" int not null
);
insert into "widget" values (default, 'Apple', '100');
insert into "widget" values (default, 'Banana', '200');
insert into "widget" values (default, 'Orange', '300');

# --- !Downs

drop table "widget" if exists;