# --- !Ups

create table "widgets" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "price" int not null
);

# --- !Downs

drop table "widgets" if exists;
